#!/bin/bash
 
NAME="bid_app"                                  # Name of the application
BASEDIR=/home/vagrant
DJANGODIR=$BASEDIR/bid             # Django project directory
SOCKFILE=$BASEDIR/venv-bid/run/gunicorn.sock  # we will communicte using this unix socket
USER=bid                                        # the user to run as
GROUP=webapps                                     # the group to run as
NUM_WORKERS=3                                     # how many worker processes should Gunicorn spawn (2*CUPU's +1)
DJANGO_SETTINGS_MODULE=bid.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=bid.wsgi                     # WSGI module name
 
echo "Starting $NAME as `whoami`"
 
# Activate the virtual environment
cd $DJANGODIR
source $BASEDIR/venv-bid/bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH
 
# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR
 
# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
echo unix:$SOCKFILE
exec $BASEDIR/venv-bid/bin/gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=unix:$SOCKFILE \
  --log-level=debug \
  --log-file=-

