language: python
python:
  # - "2.6"
  - "2.7"
services: postgresql
env:
  - DJANGO=1.7.1
install:
  - pip install -q Django==$DJANGO
  - pip install django-debug-toolbar
  - pip install PIL --allow-external PIL --allow-unverified PIL
  - pip install -r requirements.txt
  #- python setup.py -q install
before_script:
# - "pep8 --exclude=migrations --ignore=E501,E225 src"
# - pyflakes -x W src
  #- mysql -e 'create database mysite_db;'
  #- python manage.py syncdb --noinput
  - psql -c "CREATE DATABASE bid;" -U postgres
script:
  - python manage.py syncdb --noinput
  - python manage.py test
